### ISSUE TITLE
Acer Rubrum versus Acer Rubra ? / Redondant species names ?

### ISSUE THREAD

**Issue by Klemet** [allometric/allometric#187]
Hello there ! Thanks for the package, it's incredibly useful 😄 !

Looking for models for the red maple (*Acer rubrum*), I noticed that some models are indeed associated with *Acer rubrum*, but some other have the name *Acer rubra* instead. *Acer rubra* is sometimes indicated online as the red maple too, but this name doesn't seem that much used.

The main issue is that some publications (e,g. ([`lambert_2005`](https://cdnsciencepub.com/doi/10.1139/x05-112)) indicate *Acer rubrum* as the red maple in their main text, but the name *Acer rubra* is associated to their model in the database of allometric (see model `edaf7d62` for an example). This might lead to some confusion.

Maybe the name used in the publication should be prioritized ? Or maybe I'm missing something !

**Comment by brycefrank** [comment]
Hey, thanks for pointing this out. I will take a look.

I have started using `rgbif` internally for a few things. Maybe this can be a short term way to standardize the names.

https://cran.r-project.org/web/packages/rgbif/index.html

**Comment by Klemet** [comment]
Glad if it helps ! And thank you again for the wonderful package 😄 ! Many of my colleagues love it very much !

**Comment by brycefrank** [comment]
@Klemet Thank you! Glad the package is getting some traction at last.

I made the refactor in the models repository. Please run `install_models(redownload = TRUE)` to obtain the edits in your local copy. Please be aware that the model IDs are essentially hashed strings of the descriptors, among which the species names are included. So, the IDs will change and you will need to redetermine the ID. The following should get you pretty close.

```
models %>%
    dplyr::filter(pub_id == "lambert_2005") %>%
    unnest_taxa() %>%
    dplyr::filter(genus == "Acer", species == "rubrum")
```

Please, if you have any publications you want us to prioritize, submit an issue using [this template](https://github.com/allometric/models/issues/new?assignees=brycefrank&labels=add+publication&projects=&template=add-models-from-a-publication.md&title=%5BInsert+Author-Date+Citation%5D).

**Comment by Klemet** [comment]
Perfect, thank you very much Frank ! Everything works like a charm on my side with the update.

I'll be sure to use the template next time; thank you !
