### ISSUE TITLE
Create functions for querying models via API

### ISSUE THREAD

**Issue by brycefrank** [allometric/allometric#192]
The serverless API is more or less functional, and is accepting requests via HTTP.

First, we should expand the `model` endpoint to consider various arguments. We need not be expansive but the following make sense to me:

- [x] `country` - `descriptors.country`
- [x] `region` - `descriptors.region`
- [ ] `family` - `descriptors.taxa.family`
- [ ] `genus` - `descriptors.taxa.genus`
- [ ] `species` - `descriptors.taxa.species`
- [ ] `covariates` - `covariates.name`
- [ ] `response` - `response.name`
- [x] `pub_id` - `pub_id`
- [x] `model_type` - `model_type`

Here is an example call:

```
get_models(
  country = c("US", "CA"),
  model_type = c("site index"),
  genus = "Pinus",
  species = "ponderosa"
)
```

The interpretation across arguments is an AND condition. The interpretation within arguments is a `%in%` operator. For example, the call above gets all models specified for US or CA (or both) that are site index models for Ponderosa pine. Leaving an argument unspecified (in this case, e.g., `family`), means that the MongoDB will not be queried on that attribute at all. For example, imagine some hypothetical (for the sake of argument) `Betulaceae Pinus ponderosa`. This function would return site index for that hypothetical taxon as well as for `Pinaceae Pinus ponderosa`.

### Debugging in App Services

In App Service, call the function directly, e.g.: `exports({query: {country: 'US'}})`

**Comment by jwlunsford** [comment]
Bryce:

Interesting.  Let’s catch up when you have some time.  I am trying to follow all the recent changes.  I am available a few days this week or next.

Which direction did you decide on for the API - Atlas Data API or other?
How are the endpoints currently accessed?


Jon Lunsford
Mobile:  936-615-2053








On Mar 17, 2024, at 2:42 PM, Bryce Frank ***@***.***> wrote:



The serverless API is more or less functional, and is accepting requests via HTTP.

First, we should expand the model endpoint to consider various arguments. We need not be expansive but the following make sense to me:

  *   state
  *   region
  *   taxa

**Comment by brycefrank** [comment]
Migrating this to the `alloapi` repo
